# Generated by Django 3.2.10 on 2024-08-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240425_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
